import React, { Component } from 'react';

import {
    AsyncStorage,
} from 'react-native';
const questions = [{
        // FLAGS
        question: 'Which country does this flag represent?',
        img: require('../img/flag1.png'),
        corectAn: 'Macedonia',
        ans: ['Serbia', 'Macedonia', 'Spain', "Ukraine"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/flag2.png'),
        corectAn: 'Russia',
        ans: ['Slovenia', 'Brazil', 'Russia', "Ukraine"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/flag3.jpg'),
        corectAn: 'China',
        ans: ['China', 'Cuba', 'Monoglia', "Peru"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/flag4.jpg'),
        corectAn: 'Usa',
        ans: ['Usa', 'Macedonia', 'Russia', "Uk"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/flag5.png'),
        corectAn: 'Philipines',
        ans: ['Singapore', 'Vietnam', 'Philipines', "Marocco"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/urug.png'),
        corectAn: 'Uruguay',
        ans: ['Argentina', 'Uruguay', 'Nicaragua', "Honduras"],
        dificult: ['1', '2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/tajk.png'),
        corectAn: 'Tajikistan',
        ans: ['Azerbaijan', 'Uzbekistan', 'Kazakhstan', "Tajikistan"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/afganu.png'),
        corectAn: 'Afghanistan',
        ans: ['Pakistan', 'Syria', 'Libya', "Afghanistan"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/algeria.png'),
        corectAn: 'Algeria',
        ans: ['Pakistan', 'Algeria', 'Tunisia', "Egypt"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/andora.png'),
        corectAn: 'Andorra',
        ans: ['San Marino', 'Spain', 'Romania', "Andorra"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/angola.png'),
        corectAn: 'Angola',
        ans: ['Angola', 'Mozambique', 'Tanzania', "Namibia"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/argen.png'),
        corectAn: 'Argentina',
        ans: ['Uruguay', 'Argentina', 'Bolivia', "Paraguay"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/armen.png'),
        corectAn: 'Armenia',
        ans: ['Azerbaijan', 'Tajikistan', 'Iran', "Armenia"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/au.png'),
        corectAn: 'Australia',
        ans: ['Australia', 'New Zealand', 'United Kingdom', "Tasmania"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/austr.png'),
        corectAn: 'Austria',
        ans: ['Denmark', 'Austria', 'Norway', "Switzerland"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/azer.png'),
        corectAn: 'Austria',
        ans: ['Azerbaijan', 'Kazakhstan', 'Mongolia', "Georgia"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/austr.png'),
        corectAn: 'Austria',
        ans: ['Denmark', 'Austria', 'Norway', "Switzerland"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/bahr.png'),
        corectAn: 'Bahrain',
        ans: ['Qatar', 'Kuwait', 'Iraq', "Bahrain"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/bangla.png'),
        corectAn: 'Bangladesh',
        ans: ['Nepal', 'Pakistan', 'Bangladesh', "Myanmar"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/barbados.png'),
        corectAn: 'Barbados',
        ans: ['Barbados', 'Andorra', 'Dominican Republic', "Puerto Rico"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/belarus.png'),
        corectAn: 'Belarus',
        ans: ['Ukraine', 'Belarus', 'Lithuania', "Bosnia and Herzegovina"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/belgium.png'),
        corectAn: 'Belgium',
        ans: ['Belgium', 'Germany', 'Spain', "Austria"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/belizie.png'),
        corectAn: 'Belize',
        ans: ['Costa Rica', 'Bahamas', 'Barbados', "Belize"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/bhutan.png'),
        corectAn: 'Bhutan',
        ans: ['Brunei', 'Mongolia', 'Myanmar', "Bhutan"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/bolivia.png'),
        corectAn: 'Bolivia',
        ans: ['Ecuador', 'Bolivia', 'Peru', "Guatemala"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/bosna.png'),
        corectAn: 'Bosnia and Herzegovina',
        ans: ['Bosnia and Herzegovina', 'Croatia', 'Montenegro', "Greece"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/botswana.png'),
        corectAn: 'Botswana',
        ans: ['South Africa', 'Botswana', 'Zimbabwe', "Burkina Faso"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/br.png'),
        corectAn: 'Brazil',
        ans: ['Australia', 'United States', 'Brazil', "Venezuela"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/bulgaria.png'),
        corectAn: 'Bulgaria',
        ans: ['Bulgaria', 'Greece', 'Serbia', "Hungary"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/burkeine.png'),
        corectAn: 'Burkina Faso',
        ans: ['Mauritania', 'Senegal', 'Gabon', "Burkina Faso"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/cambodia.png'),
        corectAn: 'Cambodia',
        ans: ['Cambodia', 'Thailand', 'Malaysia', "Indonesia"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/cameron.png'),
        corectAn: 'Cameroon',
        ans: ['Nigeria', 'Gabon', 'Mali', "Cameroon"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/can.png'),
        corectAn: 'Canada',
        ans: ['United States', 'Canada', 'Russia', "China"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/central-african.png'),
        corectAn: 'Central African Republic',
        ans: ['Central African Republic', 'Egypt', 'Tunis', "China"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/chad.png'),
        corectAn: 'Chad',
        ans: ['Spain', 'Egypt', 'Romania', "Chad"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/chezk.png'),
        corectAn: 'Czech Republic',
        ans: ['Netherlands', 'Slovenia', 'Slovakia', "Czech Republic"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/chi.png'),
        corectAn: 'China',
        ans: ['China', 'France', 'Russia', "United States"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/chiile.png'),
        corectAn: 'Chile',
        ans: ['Peru', 'France', 'Mexico', "Chile"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/columbia.png'),
        corectAn: 'Colombia',
        ans: ['Ecuador', 'Colombia', 'Cameroon', "Paraguay"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/congo.png'),
        corectAn: 'Democratic Republic of the Congo',
        ans: ['Democratic Republic of the Congo', 'Uganda', 'Cameroon', "Sudan"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/costa.png'),
        corectAn: 'Costa Rica',
        ans: ['Costa Rica', 'Chile', 'Honduras', "Cuba"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/cote-divore.png'),
        corectAn: 'Côte d’Ivoire',
        ans: ['Senegal', 'Côte d’Ivoire', 'Liberia', "Nigeria"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/croatia.png'),
        corectAn: 'Croatia',
        ans: ['Montenegro', 'Hungary', 'Serbia', "Croatia"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/cuba.png'),
        corectAn: 'Cuba',
        ans: ['Chile', 'Dominican Republic', 'Cuba', "North Korea"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/cyprus.png'),
        corectAn: 'Cyprus',
        ans: ['Serbia', 'Cyprus', 'Cuba', "Honduras"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/denamark.png'),
        corectAn: 'Denmark',
        ans: ['Denmark', 'Switzerland', 'Austria', "Czech Republic"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/ecuador.png'),
        corectAn: 'Ecuador',
        ans: ['Uruguay', 'Bolivia', 'Colombia', "Ecuador"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/egypt.png'),
        corectAn: 'Egypt',
        ans: ['Saudi Arabia', 'Morocco', 'Egypt', "Tunisia"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/eritra.png'),
        corectAn: 'Eritrea',
        ans: ['Ethiopia', 'Morocco', 'Egypt', "Eritrea"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/estoinia.png'),
        corectAn: 'Estonia',
        ans: ['Latvia', 'Finland', 'Estonia', "Lithuania"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/ethiopia.png'),
        corectAn: 'Ethiopia',
        ans: ['Ethiopia', 'Egypt', 'Eritrea', "Morocco"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/etimor.png'),
        corectAn: 'Timor-Leste',
        ans: ['Brunei', 'Timor-Leste', 'Guinea-Bissau', "Laos"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/finland.png'),
        corectAn: 'Finland',
        ans: ['Norway', 'Sweden', 'Poland', "Finland"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/fr.png'),
        corectAn: 'France',
        ans: ['Italy', 'Belgium', 'France', "Spain"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/gabon.png'),
        corectAn: 'Gabon',
        ans: ['Gabon', 'Chad', 'Egypt', "Cameroon"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/gambia.png'),
        corectAn: 'Gambia',
        ans: ['Gabon', 'Chad', 'Guinea', "Gambia"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/ge.png'),
        corectAn: 'Germany',
        ans: ['France', 'Belgium', 'Germany', "Poland"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/gerogia.png'),
        corectAn: 'Georgia',
        ans: ['Georgia', 'Armenia', 'Turkey', "Azerbaijan"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/ghanna.png'),
        corectAn: 'Ghana',
        ans: ['Senegal', 'Chad', 'Cameroon', "Ghana"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/greece.png'),
        corectAn: 'Greece',
        ans: ['Serbia', 'Greece', 'Macedonia', "Albania"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/grenada.png'),
        corectAn: 'Grenada',
        ans: ['Grenada', 'Antigua and Barbuda', 'Macedonia', "Trinidad and Tobago"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/guatemala.png'),
        corectAn: 'Guatemala',
        ans: ['Bolivia', 'Nicaragua', 'Honduras', "Guatemala"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/guayana.png'),
        corectAn: 'Guyana',
        ans: ['Suriname', 'Barbados', 'Guyana', "Guinea"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/haiti.png'),
        corectAn: 'Haiti',
        ans: ['Haiti', 'Honduras', 'Bahamas', "Jamaica"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/honduras.png'),
        corectAn: 'Honduras',
        ans: ['Honduras', 'Nicaragua', 'Bolivia', "Jamaica"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/hungary.png'),
        corectAn: 'Hungary',
        ans: ['Hungary', 'Slovakia', 'Bolivia', "Germany"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/iceland.png'),
        corectAn: 'Iceland',
        ans: ['Iceland', 'Finland', 'New Zealand', "Faroe Islands"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/india.png'),
        corectAn: 'India',
        ans: ['China', 'India', 'Russia', "Pakistan"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/indonesia.png'),
        corectAn: 'Indonesia',
        ans: ['China', 'Cambodia', 'Singapore', "Indonesia"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/iralnd.png'),
        corectAn: 'Republic of Ireland',
        ans: ['Republic of Ireland', 'Iceland', 'Netherlands', "Italy"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/iran.png'),
        corectAn: 'Iran',
        ans: ['Oman', 'Iran', 'Iraq', "Egypt"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/iraq.png'),
        corectAn: 'Iraq',
        ans: ['Oman', 'Iran', 'Iraq', "Egypt"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/isr.png'),
        corectAn: 'Israel',
        ans: ['Israel', 'Syria', 'Jordan', "Egypt"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/it.png'),
        corectAn: 'Italy',
        ans: ['France', 'Spain', 'Italy', "Ireland"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/jamajca.png'),
        corectAn: 'Jamaica',
        ans: ['Jamaica', 'Cuba', 'Costa Rica', "Barbados"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/jordan.png'),
        corectAn: 'Jordan',
        ans: ['Syria', 'Israel', 'Oman', "Jordan"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/jp.png'),
        corectAn: 'Japan',
        ans: ['South Korea', 'China', 'Japan', "North Korea"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/kazak.png'),
        corectAn: 'Kazakhstan',
        ans: ['Kazakhstan', 'Mongolia', 'Uzbekistan', "Afghanistan"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/kenya.png'),
        corectAn: 'Kenya',
        ans: ['Sudan', 'Morocco', 'Tanzania', "Kenya"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/kuwait.png'),
        corectAn: 'Kuwait',
        ans: ['Kuwait', 'Morocco', 'Qatar', "Yemen"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/kyrgiz.png'),
        corectAn: 'Kyrgyzstan',
        ans: ['Kyrgyzstan', 'Mongolia', 'Pakistan', "Macedonia"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/laos.png'),
        corectAn: 'Laos',
        ans: ['Japan', 'Cambodia', 'Laos', "Malaysia"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/lebanon.png'),
        corectAn: 'Lebanon',
        ans: ['Egypt', 'Iran', 'Syria', "Lebanon"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/lithuania.png'),
        corectAn: 'Lithuania',
        ans: ['Lithuania', 'Estonia', 'Finland', "Lebanon"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/madagas.png'),
        corectAn: 'Madagascar',
        ans: ['Madagascar', 'Mauritius', 'Maldives', "Kenya"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/mali.png'),
        corectAn: 'Mali',
        ans: ['Togo', 'Senegal', 'Libya', "Mali"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/malta.png'),
        corectAn: 'Malta',
        ans: ['Andorra', 'Malta', 'San Marino', "Cyprus"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/mauritian.png'),
        corectAn: 'Mauritania',
        ans: ['Bahamas', 'Malta', 'Maldives', "Mauritania"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/micua.png'),
        corectAn: 'Nicaragua',
        ans: ['Costa Rica', 'El Salvador', 'Nicaragua', "Mauritania"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/moldova.png'),
        corectAn: 'Moldova',
        ans: ['Montenegro', 'Albania', 'Ukraine', "Moldova"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/mongolia.png'),
        corectAn: 'Mongolia',
        ans: ['China', 'Mongolia', 'Kazakhstan', "Kyrgyzstan"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/morooco.png'),
        corectAn: 'Morocco',
        ans: ['Libya', 'Tunisia', 'Algeria', "Morocco"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/nambia.png'),
        corectAn: 'Namibia',
        ans: ['Namibia', 'South Africa', 'Angola', "Uganda"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/nepal.png'),
        corectAn: 'Nepal',
        ans: ['Myanmar', 'India', 'Cambodia', "Nepal"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/niger.png'),
        corectAn: 'Nepal',
        ans: ['Nigeria', 'Niger', 'Cameroon', "Senegal"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/oman.png'),
        corectAn: 'Oman',
        ans: ['Lebanon', 'Yemen', 'Oman', "Iran"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/panama.png'),
        corectAn: 'Panama',
        ans: ['Panama', 'Nicaragua', 'Costa Rica', "Venezuela"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/romania.png'),
        corectAn: 'Romania',
        ans: ['Moldova', 'Chad', 'Romania', "France"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/rwanda.png'),
        corectAn: 'Rwanda',
        ans: ['Madagascar', 'Angola', 'Uganda', "Rwanda"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/saudi.png'),
        corectAn: 'Saudi Arabia',
        ans: ['Saudi Arabia', 'Iran', 'Bahrain', "Kuwait"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/sc.png'),
        corectAn: 'South Korea',
        ans: ['South Korea', 'North Korea', 'Myanmar', "Japan"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/serbia.png'),
        corectAn: 'Serbia',
        ans: ['Bulgaria', 'Macedonia', 'Serbia', "Croatia"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/slovakia.png'),
        corectAn: 'Slovakia',
        ans: ['Slovakia', 'Czech', 'Serbia', "Slovenia"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/slovenia.png'),
        corectAn: 'Slovenia',
        ans: ['Slovakia', 'Czech', 'Serbia', "Slovenia"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/somalia.png'),
        corectAn: 'Somalia',
        ans: ['Ethiopia', 'Somalia', 'Eritrea', "Egypt"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/spain.png'),
        corectAn: 'Spain',
        ans: ['Germany', 'Italy', 'Spain', "France"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/srilanka.png'),
        corectAn: 'Sri Lanka',
        ans: ['Sri Lanka', 'Malta', 'India', "Andorra"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/ss.png'),
        corectAn: 'South Sudan',
        ans: ['South Sudan', 'Sudan', 'Ethiopia', "Egypt"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/sudan.png'),
        corectAn: 'Sudan',
        ans: ['Sudan', 'South Sudan', 'Ethiopia', "Egypt"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/swaziland.png'),
        corectAn: 'Swaziland',
        ans: ['Sudan', 'Botswana', 'Swaziland', "Zambia"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/swic.png'),
        corectAn: 'Switzerland',
        ans: ['Italy', 'Austria', 'Australia', "Switzerland"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/syria.png'),
        corectAn: 'Syria',
        ans: ['Jordan', 'Yemen', 'Syria', "Lebanon"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/taiwan.png'),
        corectAn: 'Taiwan',
        ans: ['Thailand', 'Myanmar', 'Taiwan', "China"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/tajk.png'),
        corectAn: 'Tajikistan',
        ans: ['Afghanistan', 'Kazakhstan', 'Uzbekistan', "Tajikistan"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/togo.png'),
        corectAn: 'Togo',
        ans: ['Togo', 'Benin', 'Ghana', "Gabon"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/tunis.png'),
        corectAn: 'Tunis',
        ans: ['Turkey', 'Tunis', 'Marocco', "Algeria"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/turkey.png'),
        corectAn: 'Turkey',
        ans: ['Turkey', 'Tunis', 'Sudan', "Egypt"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/uganda.png'),
        corectAn: 'Uganda',
        ans: ['Cameroon', 'Tanzania', 'Kenya', "Uganda"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/uk.png'),
        corectAn: 'United Kingdom',
        ans: ['United States', 'United Kingdom', 'France', "Russia"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/ukraine.png'),
        corectAn: 'Ukraine',
        ans: ['Romania', 'Belarus', 'Ukraine', "Russia"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/urug.png'),
        corectAn: 'Uruguay',
        ans: ['Uruguay', 'Argentina', 'Paraguay', "Peru"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/vene.png'),
        corectAn: 'Venezuela',
        ans: ['Uruguay', 'Argentina', 'Venezuela', "Chile"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/viet.png'),
        corectAn: 'Vietnam',
        ans: ['Cambodia', 'Thailand', 'Myanmar', "Vietnam"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/yemen.png'),
        corectAn: 'Yemen',
        ans: ['Oman', 'Yemen', 'Egypt', "Syria"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/zimbab.png'),
        corectAn: 'Zimbabwe',
        ans: ['Botswana', 'Senegal', 'Mozambique', "Zimbabwe"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    // RIVERS
    {
        question: 'What is the longest river in the world?',
        img: require('../img/river.jpg'),
        corectAn: 'Nile',
        ans: ['Mississippi', 'Yangtze', 'Nile', "Amazon"],
        dificult: ['1', '2'],
        type: 'river',
    },
];
var dif;
var difArray = [];
var easyQuest = [];
var normalQuest = [];
var hardQuest = [];
var difQuest_1 = [];
var difQuest_2 = [];
var difQuest_3 = [];
// AsyncStorage.getItem('dificult').then((data) => {
//     dif = data;
//     difarr();
// })

function difarr() {
    for (let x = 0; x < questions.length; x++) {
        if (questions[x].dificult.includes('1')) {
            easyQuest.push(questions[x]);
        }
        if (questions[x].dificult.includes('2')) {
            normalQuest.push(questions[x]);
        }
        if (questions[x].dificult.includes('3')) {
            hardQuest.push(questions[x]);
        }

    }
    random();
}

function random() {
    for (let i = 0; i < 5; i++) {
        let num = Math.floor(Math.random() * easyQuest.length);
        difQuest_1.push(easyQuest[num]);
        easyQuest.splice(num, 1);
    }
    for (let i = 0; i < 5; i++) {
        let num = Math.floor(Math.random() * normalQuest.length);
        difQuest_2.push(normalQuest[num]);
        normalQuest.splice(num, 1);
    }
    for (let i = 0; i < 5; i++) {
        let num = Math.floor(Math.random() * hardQuest.length);
        difQuest_3.push(hardQuest[num]);
        hardQuest.splice(num, 1);
    }
    return difQuest_1, difQuest_2, difQuest_3;
}
difarr();
// random();
var dificulties = [difQuest_1, difQuest_2, difQuest_3]
console.log(dificulties);
export { dificulties };