import React, { Component } from 'react';

import {
    AsyncStorage,
} from 'react-native';
const questions = [{
        // FLAGS
        question: 'Which country does this flag represent?',
        img: require('../img/flag1.png'),
        corectAn: 'Macedonia',
        ans: ['Serbia', 'Macedonia', 'Spain', "Ukraine"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/flag2.png'),
        corectAn: 'Russia',
        ans: ['Slovenia', 'Brazil', 'Russia', "Ukraine"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/flag3.jpg'),
        corectAn: 'China',
        ans: ['China', 'Cuba', 'Monoglia', "Peru"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/flag4.jpg'),
        corectAn: 'Usa',
        ans: ['Usa', 'Macedonia', 'Russia', "Uk"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/flag5.png'),
        corectAn: 'Philipines',
        ans: ['Singapore', 'Vietnam', 'Philipines', "Marocco"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/thiland.png'),
        corectAn: 'Thailand',
        ans: ['Thailand', 'Vietnam', 'Philipines', "Marocco"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/urug.png'),
        corectAn: 'Uruguay',
        ans: ['Argentina', 'Uruguay', 'Nicaragua', "Honduras"],
        dificult: ['1', '2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/tajk.png'),
        corectAn: 'Tajikistan',
        ans: ['Azerbaijan', 'Uzbekistan', 'Kazakhstan', "Tajikistan"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/afganu.png'),
        corectAn: 'Afghanistan',
        ans: ['Pakistan', 'Syria', 'Libya', "Afghanistan"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/algeria.png'),
        corectAn: 'Algeria',
        ans: ['Pakistan', 'Algeria', 'Tunisia', "Egypt"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/andora.png'),
        corectAn: 'Andorra',
        ans: ['San Marino', 'Spain', 'Romania', "Andorra"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/angola.png'),
        corectAn: 'Angola',
        ans: ['Angola', 'Mozambique', 'Tanzania', "Namibia"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/argen.png'),
        corectAn: 'Argentina',
        ans: ['Uruguay', 'Argentina', 'Bolivia', "Paraguay"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/armen.png'),
        corectAn: 'Armenia',
        ans: ['Azerbaijan', 'Tajikistan', 'Iran', "Armenia"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/au.png'),
        corectAn: 'Australia',
        ans: ['Australia', 'New Zealand', 'United Kingdom', "Tasmania"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/austr.png'),
        corectAn: 'Austria',
        ans: ['Denmark', 'Austria', 'Norway', "Switzerland"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/azer.png'),
        corectAn: 'Austria',
        ans: ['Azerbaijan', 'Kazakhstan', 'Mongolia', "Georgia"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/austr.png'),
        corectAn: 'Austria',
        ans: ['Denmark', 'Austria', 'Norway', "Switzerland"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/bahr.png'),
        corectAn: 'Bahrain',
        ans: ['Qatar', 'Kuwait', 'Iraq', "Bahrain"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/bangla.png'),
        corectAn: 'Bangladesh',
        ans: ['Nepal', 'Pakistan', 'Bangladesh', "Myanmar"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/barbados.png'),
        corectAn: 'Barbados',
        ans: ['Barbados', 'Andorra', 'Dominican Republic', "Puerto Rico"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/belarus.png'),
        corectAn: 'Belarus',
        ans: ['Ukraine', 'Belarus', 'Lithuania', "Bosnia and Herzegovina"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/belgium.png'),
        corectAn: 'Belgium',
        ans: ['Belgium', 'Germany', 'Spain', "Austria"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/belizie.png'),
        corectAn: 'Belize',
        ans: ['Costa Rica', 'Bahamas', 'Barbados', "Belize"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/bhutan.png'),
        corectAn: 'Bhutan',
        ans: ['Brunei', 'Mongolia', 'Myanmar', "Bhutan"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/bolivia.png'),
        corectAn: 'Bolivia',
        ans: ['Ecuador', 'Bolivia', 'Peru', "Guatemala"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/bosna.png'),
        corectAn: 'Bosnia and Herzegovina',
        ans: ['Bosnia and Herzegovina', 'Croatia', 'Montenegro', "Greece"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/botswana.png'),
        corectAn: 'Botswana',
        ans: ['South Africa', 'Botswana', 'Zimbabwe', "Burkina Faso"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/br.png'),
        corectAn: 'Brazil',
        ans: ['Australia', 'United States', 'Brazil', "Venezuela"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/bulgaria.png'),
        corectAn: 'Bulgaria',
        ans: ['Bulgaria', 'Greece', 'Serbia', "Hungary"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/burkeine.png'),
        corectAn: 'Burkina Faso',
        ans: ['Mauritania', 'Senegal', 'Gabon', "Burkina Faso"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/cambodia.png'),
        corectAn: 'Cambodia',
        ans: ['Cambodia', 'Thailand', 'Malaysia', "Indonesia"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/cameron.png'),
        corectAn: 'Cameroon',
        ans: ['Nigeria', 'Gabon', 'Mali', "Cameroon"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/can.png'),
        corectAn: 'Canada',
        ans: ['United States', 'Canada', 'Russia', "China"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/central-african.png'),
        corectAn: 'Central African Republic',
        ans: ['Central African Republic', 'Egypt', 'Tunis', "China"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/chad.png'),
        corectAn: 'Chad',
        ans: ['Spain', 'Egypt', 'Romania', "Chad"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/chezk.png'),
        corectAn: 'Czech Republic',
        ans: ['Netherlands', 'Slovenia', 'Slovakia', "Czech Republic"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/chi.png'),
        corectAn: 'China',
        ans: ['China', 'France', 'Russia', "United States"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/chiile.png'),
        corectAn: 'Chile',
        ans: ['Peru', 'France', 'Mexico', "Chile"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/columbia.png'),
        corectAn: 'Colombia',
        ans: ['Ecuador', 'Colombia', 'Cameroon', "Paraguay"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/congo.png'),
        corectAn: 'Democratic Republic of the Congo',
        ans: ['Democratic Republic of the Congo', 'Uganda', 'Cameroon', "Sudan"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/costa.png'),
        corectAn: 'Costa Rica',
        ans: ['Costa Rica', 'Chile', 'Honduras', "Cuba"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/cote-divore.png'),
        corectAn: 'Côte d’Ivoire',
        ans: ['Senegal', 'Côte d’Ivoire', 'Liberia', "Nigeria"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/croatia.png'),
        corectAn: 'Croatia',
        ans: ['Montenegro', 'Hungary', 'Serbia', "Croatia"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/cuba.png'),
        corectAn: 'Cuba',
        ans: ['Chile', 'Dominican Republic', 'Cuba', "North Korea"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/cyprus.png'),
        corectAn: 'Cyprus',
        ans: ['Serbia', 'Cyprus', 'Cuba', "Honduras"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/denamark.png'),
        corectAn: 'Denmark',
        ans: ['Denmark', 'Switzerland', 'Austria', "Czech Republic"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/ecuador.png'),
        corectAn: 'Ecuador',
        ans: ['Uruguay', 'Bolivia', 'Colombia', "Ecuador"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/egypt.png'),
        corectAn: 'Egypt',
        ans: ['Saudi Arabia', 'Morocco', 'Egypt', "Tunisia"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/eritra.png'),
        corectAn: 'Eritrea',
        ans: ['Ethiopia', 'Morocco', 'Egypt', "Eritrea"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/estoinia.png'),
        corectAn: 'Estonia',
        ans: ['Latvia', 'Finland', 'Estonia', "Lithuania"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/ethiopia.png'),
        corectAn: 'Ethiopia',
        ans: ['Ethiopia', 'Egypt', 'Eritrea', "Morocco"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/etimor.png'),
        corectAn: 'Timor-Leste',
        ans: ['Brunei', 'Timor-Leste', 'Guinea-Bissau', "Laos"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/finland.png'),
        corectAn: 'Finland',
        ans: ['Norway', 'Sweden', 'Poland', "Finland"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/fr.png'),
        corectAn: 'France',
        ans: ['Italy', 'Belgium', 'France', "Spain"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/gabon.png'),
        corectAn: 'Gabon',
        ans: ['Gabon', 'Chad', 'Egypt', "Cameroon"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/gambia.png'),
        corectAn: 'Gambia',
        ans: ['Gabon', 'Chad', 'Guinea', "Gambia"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/ge.png'),
        corectAn: 'Germany',
        ans: ['France', 'Belgium', 'Germany', "Poland"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/gerogia.png'),
        corectAn: 'Georgia',
        ans: ['Georgia', 'Armenia', 'Turkey', "Azerbaijan"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/ghanna.png'),
        corectAn: 'Ghana',
        ans: ['Senegal', 'Chad', 'Cameroon', "Ghana"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/greece.png'),
        corectAn: 'Greece',
        ans: ['Serbia', 'Greece', 'Macedonia', "Albania"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/alb.png'),
        corectAn: 'Albania',
        ans: ['Serbia', 'Greece', 'Macedonia', "Albania"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/grenada.png'),
        corectAn: 'Grenada',
        ans: ['Grenada', 'Antigua and Barbuda', 'Macedonia', "Trinidad and Tobago"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/guatemala.png'),
        corectAn: 'Guatemala',
        ans: ['Bolivia', 'Nicaragua', 'Honduras', "Guatemala"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/guayana.png'),
        corectAn: 'Guyana',
        ans: ['Suriname', 'Barbados', 'Guyana', "Guinea"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/haiti.png'),
        corectAn: 'Haiti',
        ans: ['Haiti', 'Honduras', 'Bahamas', "Jamaica"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/honduras.png'),
        corectAn: 'Honduras',
        ans: ['Honduras', 'Nicaragua', 'Bolivia', "Jamaica"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/hungary.png'),
        corectAn: 'Hungary',
        ans: ['Hungary', 'Slovakia', 'Bolivia', "Germany"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/iceland.png'),
        corectAn: 'Iceland',
        ans: ['Iceland', 'Finland', 'New Zealand', "Faroe Islands"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/india.png'),
        corectAn: 'India',
        ans: ['China', 'India', 'Russia', "Pakistan"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/indonesia.png'),
        corectAn: 'Indonesia',
        ans: ['China', 'Cambodia', 'Singapore', "Indonesia"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/iralnd.png'),
        corectAn: 'Republic of Ireland',
        ans: ['Republic of Ireland', 'Iceland', 'Netherlands', "Italy"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/iran.png'),
        corectAn: 'Iran',
        ans: ['Oman', 'Iran', 'Iraq', "Egypt"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/iraq.png'),
        corectAn: 'Iraq',
        ans: ['Oman', 'Iran', 'Iraq', "Egypt"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/isr.png'),
        corectAn: 'Israel',
        ans: ['Israel', 'Syria', 'Jordan', "Egypt"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/it.png'),
        corectAn: 'Italy',
        ans: ['France', 'Spain', 'Italy', "Ireland"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/jamajca.png'),
        corectAn: 'Jamaica',
        ans: ['Jamaica', 'Cuba', 'Costa Rica', "Barbados"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/jordan.png'),
        corectAn: 'Jordan',
        ans: ['Syria', 'Israel', 'Oman', "Jordan"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/jp.png'),
        corectAn: 'Japan',
        ans: ['South Korea', 'China', 'Japan', "North Korea"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/kazak.png'),
        corectAn: 'Kazakhstan',
        ans: ['Kazakhstan', 'Mongolia', 'Uzbekistan', "Afghanistan"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/kenya.png'),
        corectAn: 'Kenya',
        ans: ['Sudan', 'Morocco', 'Tanzania', "Kenya"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/kuwait.png'),
        corectAn: 'Kuwait',
        ans: ['Kuwait', 'Morocco', 'Qatar', "Yemen"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/kyrgiz.png'),
        corectAn: 'Kyrgyzstan',
        ans: ['Kyrgyzstan', 'Mongolia', 'Pakistan', "Macedonia"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/laos.png'),
        corectAn: 'Laos',
        ans: ['Japan', 'Cambodia', 'Laos', "Malaysia"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/lebanon.png'),
        corectAn: 'Lebanon',
        ans: ['Egypt', 'Iran', 'Syria', "Lebanon"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/lithuania.png'),
        corectAn: 'Lithuania',
        ans: ['Lithuania', 'Estonia', 'Finland', "Lebanon"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/madagas.png'),
        corectAn: 'Madagascar',
        ans: ['Madagascar', 'Mauritius', 'Maldives', "Kenya"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/mali.png'),
        corectAn: 'Mali',
        ans: ['Togo', 'Senegal', 'Libya', "Mali"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/malta.png'),
        corectAn: 'Malta',
        ans: ['Andorra', 'Malta', 'San Marino', "Cyprus"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/mauritian.png'),
        corectAn: 'Mauritania',
        ans: ['Bahamas', 'Malta', 'Maldives', "Mauritania"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/micua.png'),
        corectAn: 'Nicaragua',
        ans: ['Costa Rica', 'El Salvador', 'Nicaragua', "Mauritania"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/moldova.png'),
        corectAn: 'Moldova',
        ans: ['Montenegro', 'Albania', 'Ukraine', "Moldova"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/mongolia.png'),
        corectAn: 'Mongolia',
        ans: ['China', 'Mongolia', 'Kazakhstan', "Kyrgyzstan"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/morooco.png'),
        corectAn: 'Morocco',
        ans: ['Libya', 'Tunisia', 'Algeria', "Morocco"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/nambia.png'),
        corectAn: 'Namibia',
        ans: ['Namibia', 'South Africa', 'Angola', "Uganda"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/nepal.png'),
        corectAn: 'Nepal',
        ans: ['Myanmar', 'India', 'Cambodia', "Nepal"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/niger.png'),
        corectAn: 'Nepal',
        ans: ['Nigeria', 'Niger', 'Cameroon', "Senegal"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/oman.png'),
        corectAn: 'Oman',
        ans: ['Lebanon', 'Yemen', 'Oman', "Iran"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/panama.png'),
        corectAn: 'Panama',
        ans: ['Panama', 'Nicaragua', 'Costa Rica', "Venezuela"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/romania.png'),
        corectAn: 'Romania',
        ans: ['Moldova', 'Chad', 'Romania', "France"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/rwanda.png'),
        corectAn: 'Rwanda',
        ans: ['Madagascar', 'Angola', 'Uganda', "Rwanda"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/saudi.png'),
        corectAn: 'Saudi Arabia',
        ans: ['Saudi Arabia', 'Iran', 'Bahrain', "Kuwait"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/sc.png'),
        corectAn: 'South Korea',
        ans: ['South Korea', 'North Korea', 'Myanmar', "Japan"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/serbia.png'),
        corectAn: 'Serbia',
        ans: ['Bulgaria', 'Macedonia', 'Serbia', "Croatia"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/slovakia.png'),
        corectAn: 'Slovakia',
        ans: ['Slovakia', 'Czech', 'Serbia', "Slovenia"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/slovenia.png'),
        corectAn: 'Slovenia',
        ans: ['Slovakia', 'Czech', 'Serbia', "Slovenia"],
        dificult: ['2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/somalia.png'),
        corectAn: 'Somalia',
        ans: ['Ethiopia', 'Somalia', 'Eritrea', "Egypt"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/spain.png'),
        corectAn: 'Spain',
        ans: ['Germany', 'Italy', 'Spain', "France"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/srilanka.png'),
        corectAn: 'Sri Lanka',
        ans: ['Sri Lanka', 'Malta', 'India', "Andorra"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/ss.png'),
        corectAn: 'South Sudan',
        ans: ['South Sudan', 'Sudan', 'Ethiopia', "Egypt"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/sudan.png'),
        corectAn: 'Sudan',
        ans: ['Sudan', 'South Sudan', 'Ethiopia', "Egypt"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/swaziland.png'),
        corectAn: 'Swaziland',
        ans: ['Sudan', 'Botswana', 'Swaziland', "Zambia"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/swic.png'),
        corectAn: 'Switzerland',
        ans: ['Italy', 'Austria', 'Australia', "Switzerland"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/syria.png'),
        corectAn: 'Syria',
        ans: ['Jordan', 'Yemen', 'Syria', "Lebanon"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/t.png'),
        corectAn: 'Taiwan',
        ans: ['Thailand', 'Myanmar', 'Taiwan', "China"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/tajk.png'),
        corectAn: 'Tajikistan',
        ans: ['Afghanistan', 'Kazakhstan', 'Uzbekistan', "Tajikistan"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/togo.png'),
        corectAn: 'Togo',
        ans: ['Togo', 'Benin', 'Ghana', "Gabon"],
        dificult: ['3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/tunis.png'),
        corectAn: 'Tunis',
        ans: ['Turkey', 'Tunis', 'Marocco', "Algeria"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/turkey.png'),
        corectAn: 'Turkey',
        ans: ['Turkey', 'Tunis', 'Sudan', "Egypt"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/uganda.png'),
        corectAn: 'Uganda',
        ans: ['Cameroon', 'Tanzania', 'Kenya', "Uganda"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/uk.png'),
        corectAn: 'United Kingdom',
        ans: ['United States', 'United Kingdom', 'France', "Russia"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/ukraine.png'),
        corectAn: 'Ukraine',
        ans: ['Romania', 'Belarus', 'Ukraine', "Russia"],
        dificult: ['1'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/urug.png'),
        corectAn: 'Uruguay',
        ans: ['Uruguay', 'Argentina', 'Paraguay', "Peru"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/vene.png'),
        corectAn: 'Venezuela',
        ans: ['Uruguay', 'Argentina', 'Venezuela', "Chile"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/viet.png'),
        corectAn: 'Vietnam',
        ans: ['Cambodia', 'Thailand', 'Myanmar', "Vietnam"],
        dificult: ['1', '2'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/yemen.png'),
        corectAn: 'Yemen',
        ans: ['Oman', 'Yemen', 'Egypt', "Syria"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    {
        question: 'Which country does this flag represent?',
        img: require('../img/zimbab.png'),
        corectAn: 'Zimbabwe',
        ans: ['Botswana', 'Senegal', 'Mozambique', "Zimbabwe"],
        dificult: ['2', '3'],
        type: 'flag',
    },
    //Country

    //Capitals
    {
        question: 'What is the Capital of Russia?',
        img: require('../img/flag2.png'),
        corectAn: 'Moscow',
        ans: ['Vladivostok', 'St. Petersburg', 'Yekaterinburg', "Moscow"],
        dificult: ['1', '2'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Albania?',
        img: require('../img/alb.png'),
        corectAn: 'Tirana',
        ans: ['Ankara', 'Sofia', 'Athena', "Tirana"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Macedonia?',
        img: require('../img/flag1.png'),
        corectAn: 'Skopje',
        ans: ['Skopje', 'Bitola', 'Tetovo', "Ohrid"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Argentina?',
        img: require('../img/argen.png'),
        corectAn: 'Buenos Aires',
        ans: ['Lima', 'Santiago', 'Salta', "Buenos Aires"],
        dificult: ['1', '2'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Afganistan?',
        img: require('../img/afganu.png'),
        corectAn: 'Kabul',
        ans: ['Kandahar', 'Karachi', 'Kabul', "Lahore"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Algeria?',
        img: require('../img/algeria.png'),
        corectAn: 'Algiers',
        ans: ['Cairo', 'Algiers', 'Rabat', "Tunis"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Angola?',
        img: require('../img/angola.png'),
        corectAn: 'Luanda',
        ans: ['Luanda', 'Maputo', 'Rabat', "Cape Town"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Armenia?',
        img: require('../img/armen.png'),
        corectAn: 'Yerevan',
        ans: ['Tbilisi', 'Baku', 'Qabala', "Yerevan"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Australia?',
        img: require('../img/au.png'),
        corectAn: 'Canberra',
        ans: ['Melbourne', 'Perth', 'Canberra', "Sydney"],
        dificult: ['1', '2'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Austria?',
        img: require('../img/austr.png'),
        corectAn: 'Vienna',
        ans: ['Vienna', 'Perth', 'Prague', "Budapest"],
        dificult: ['1'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Azerbaijan?',
        img: require('../img/azer.png'),
        corectAn: 'Baku',
        ans: ['Tbilisi', 'Baku', 'Qabala', "Yerevan"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Georgia?',
        img: require('../img/gerogia.png'),
        corectAn: 'Tbilisi',
        ans: ['Tbilisi', 'Baku', 'Qabala', "Yerevan"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Bangladesh?',
        img: require('../img/bangla.png'),
        corectAn: 'Dhaka',
        ans: ['Sylhet', 'Dhaka', 'Khulna', "Lahore"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Belarus?',
        img: require('../img/belarus.png'),
        corectAn: 'Minsk',
        ans: ['Brest', 'Kiev', 'Moscow', "Minsk"],
        dificult: ['1', '2'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Bosnia and Herzegovina?',
        img: require('../img/bosna.png'),
        corectAn: 'Sarajevo',
        ans: ['Zagreb', 'Belgrade', 'Sarajevo', "Skopje"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Belgium?',
        img: require('../img/belgium.png'),
        corectAn: 'Brussels',
        ans: ['Bruges', 'Amsterdam', 'Antwerp', "Brussels"],
        dificult: ['1', '2'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Bolivia?',
        img: require('../img/bolivia.png'),
        corectAn: 'Sucre',
        ans: ['Mexico City', 'La Paz', 'Lima', "Sucre"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Brazil?',
        img: require('../img/br.png'),
        corectAn: 'Brasília',
        ans: ['Brasília', 'Rio de Janeiro', 'Lima', "São Paulo"],
        dificult: ['1', '2'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Bulgaria?',
        img: require('../img/bulgaria.png'),
        corectAn: 'Sofia',
        ans: ['Belgrade', 'Varna', 'Skopje', "Sofia"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Serbia?',
        img: require('../img/serbia.png'),
        corectAn: 'Belgrade',
        ans: ['Belgrade', 'Zagreb', 'Skopje', "Sofia"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Croatia?',
        img: require('../img/croatia.png'),
        corectAn: 'Zagreb',
        ans: ['Belgrade', 'Zagreb', 'Podgorica', "Split"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Czech Republic?',
        img: require('../img/chezk.png'),
        corectAn: 'Prague',
        ans: ['Prague', 'Bratislava', 'Budapest', "Warsaw"],
        dificult: ['1', '2'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Slovakia?',
        img: require('../img/slovakia.png'),
        corectAn: 'Bratislava',
        ans: ['Prague', 'Bratislava', 'Budapest', "Warsaw"],
        dificult: ['2'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Hunagry?',
        img: require('../img/hungary.png'),
        corectAn: 'Budapest',
        ans: ['Prague', 'Bratislava', 'Budapest', "Warsaw"],
        dificult: ['1', '2'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Poland?',
        img: require('../img/poland.png'),
        corectAn: 'Warsaw',
        ans: ['Prague', 'Kiev', 'Budapest', "Warsaw"],
        dificult: ['1', '2'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Ukraine?',
        img: require('../img/ukraine.png'),
        corectAn: 'Kiev',
        ans: ['Prague', 'Kiev', 'Moscow', "Minsk"],
        dificult: ['2'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Turkey?',
        img: require('../img/turkey.png'),
        corectAn: 'Ankara',
        ans: ['Ankara', 'Cairo', 'Istanbul', "Damascus"],
        dificult: ['2'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Syria?',
        img: require('../img/syria.png'),
        corectAn: 'Damascus',
        ans: ['Beirut', 'Cairo', 'Aleppo', "Damascus"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Lebanon?',
        img: require('../img/lebanon.png'),
        corectAn: 'Beirut',
        ans: ['Beirut', 'Cairo', 'Jerusalem', "Damascus"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Venezuela?',
        img: require('../img/vene.png'),
        corectAn: 'Caracas',
        ans: ['Caracas', 'Bogotá', 'Lima', "Maracay"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Thailand?',
        img: require('../img/thiland.png'),
        corectAn: 'Bangkok',
        ans: ['Ho chi minh', 'Hanoi', 'Pattaya', "Bangkok"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Egypt?',
        img: require('../img/egypt.png'),
        corectAn: 'Cairo',
        ans: ['Doha', 'Cairo', 'Jerusalem', "Alexandria"],
        dificult: ['1', '2'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of China?',
        img: require('../img/chi.png'),
        corectAn: 'Beijing',
        ans: ['Shenzhen', 'Shanghai', 'Tokyo', "Beijing"],
        dificult: ['1'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Japan?',
        img: require('../img/jp.png'),
        corectAn: 'Tokyo',
        ans: ['Kyoto', 'Seoul', 'Tokyo', "Beijing"],
        dificult: ['1'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of South Korea?',
        img: require('../img/sc.png'),
        corectAn: 'Seoul',
        ans: ['Pyongyang', 'Seoul', 'Tokyo', "Beijing"],
        dificult: ['1'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Mongolia?',
        img: require('../img/mongolia.png'),
        corectAn: 'Ulaanbaatar',
        ans: ['Tehran', 'Astana', 'Ulaanbaatar', "Beijing"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Kazakhstan?',
        img: require('../img/kazak.png'),
        corectAn: 'Astana',
        ans: ['Tehran', 'Astana', 'Ulaanbaatar', "Dushanbe"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Tajikistan?',
        img: require('../img/tajk.png'),
        corectAn: 'Dushanbe',
        ans: ['Tehran', 'Tashkent', 'Ulaanbaatar', "Dushanbe"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Iran?',
        img: require('../img/iran.png'),
        corectAn: 'Tehran',
        ans: ['Tehran', 'Tashkent', 'Baghdad', "Riyadh"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Iraq?',
        img: require('../img/iraq.png'),
        corectAn: 'Baghdad',
        ans: ['Tehran', 'Doha', 'Baghdad', "Riyadh"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Saudi Arabia?',
        img: require('../img/saudi.png'),
        corectAn: 'Riyadh',
        ans: ['Cairo', 'Doha', 'Baghdad', "Riyadh"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Kuwait?',
        img: require('../img/kuwait.png'),
        corectAn: 'Kuwait City',
        ans: ['Cairo', 'Doha', 'Kuwait City', "Riyadh"],
        dificult: ['2'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Morocco?',
        img: require('../img/morooco.png'),
        corectAn: 'Rabat',
        ans: ['Cairo', 'Rabat', 'Algiers', "Casablanca"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Tunisia?',
        img: require('../img/tunis.png'),
        corectAn: 'Tunis',
        ans: ['Cairo', 'Rabat', 'Algiers', "Tunis"],
        dificult: ['1', '2'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of United Kingdom?',
        img: require('../img/uk.png'),
        corectAn: 'London',
        ans: ['London', 'Liverpool', 'Dublin', "Cardiff"],
        dificult: ['1'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of France?',
        img: require('../img/fr.png'),
        corectAn: 'Paris',
        ans: ['London', 'Paris', 'Lyon', "Berlin"],
        dificult: ['1'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Germany?',
        img: require('../img/ge.png'),
        corectAn: 'Berlin',
        ans: ['London', 'Paris', 'Hamburg', "Berlin"],
        dificult: ['1'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of USA?',
        img: require('../img/flag4.jpg'),
        corectAn: 'Washington',
        ans: ['New York', 'Miami', 'Washington', "Los Angeles"],
        dificult: ['1'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Canada?',
        img: require('../img/can.png'),
        corectAn: 'Ottawa',
        ans: ['Toronto', 'Ottawa', 'Vancouver', "Montreal"],
        dificult: ['1'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Oman?',
        img: require('../img/oman.png'),
        corectAn: 'Muscat',
        ans: ['Muscat', 'Salalah', 'Dubai', "Doha"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Yemen?',
        img: require('../img/yemen.png'),
        corectAn: 'Sanaa',
        ans: ['Sanaa', 'Salalah', 'Tehran', "Doha"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Cambodia?',
        img: require('../img/cambodia.png'),
        corectAn: 'Phnom Penh',
        ans: ['Siem Reap', 'Hanoi', 'Ho Chi Minh', "Phnom Penh"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Vietnam?',
        img: require('../img/viet.png'),
        corectAn: 'Hanoi',
        ans: ['Siem Reap', 'Hanoi', 'Ho Chi Minh', "Phnom Penh"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Uganda?',
        img: require('../img/uganda.png'),
        corectAn: 'Kampala',
        ans: ['Kampala', 'Kigali', 'Nairobi', "Addis Ababa"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Ethiopia?',
        img: require('../img/ethiopia.png'),
        corectAn: 'Addis Ababa',
        ans: ['Asmara', 'Kigali', 'Nairobi', "Addis Ababa"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Eritrea?',
        img: require('../img/eritra.png'),
        corectAn: 'Asmara',
        ans: ['Asmara', 'Kigali', 'Nairobi', "Addis Ababa"],
        dificult: ['3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Kenya?',
        img: require('../img/kenya.png'),
        corectAn: 'Nairobi',
        ans: ['Asmara', 'Kigali', 'Nairobi', "Niamey"],
        dificult: ['3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Niger?',
        img: require('../img/niger.png'),
        corectAn: 'Niamey',
        ans: ['Yaoundé', 'Kigali', 'Nairobi', "Niamey"],
        dificult: ['3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Cameroon?',
        img: require('../img/cameron.png'),
        corectAn: 'Yaoundé',
        ans: ['Yaoundé', 'Kigali', 'Nairobi', "Niamey"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Zimbabwe?',
        img: require('../img/zimbab.png'),
        corectAn: 'Harare',
        ans: ['Yaoundé', 'Kigali', 'Nairobi', "Harare"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of D.R Congo?',
        img: require('../img/congo.png'),
        corectAn: 'Kinshasa',
        ans: ['Yaoundé', 'Kigali', 'Kinshasa', "Harare"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Gabon?',
        img: require('../img/gabon.png'),
        corectAn: 'Libreville',
        ans: ['Yaoundé', 'Mogadishu', 'Cairo', "Libreville"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Somalia?',
        img: require('../img/somalia.png'),
        corectAn: 'Mogadishu',
        ans: ['Yaoundé', 'Mogadishu', 'Banjul', "Libreville"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Gambia?',
        img: require('../img/gambia.png'),
        corectAn: 'Banjul',
        ans: ['Yaoundé', 'Mogadishu', 'Banjul', "Accra"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Ghana?',
        img: require('../img/ghanna.png'),
        corectAn: 'Accra',
        ans: ['Windhoek', 'Mogadishu', 'Banjul', "Accra"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Nambia?',
        img: require('../img/nambia.png'),
        corectAn: 'Windhoek',
        ans: ['Windhoek', 'Mogadishu', 'Banjul', "Accra"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Panama?',
        img: require('../img/panama.png'),
        corectAn: 'Panama',
        ans: ['Panama', 'San José', 'San Juan', "Havana"],
        dificult: ['1', '2'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Cuba?',
        img: require('../img/cuba.png'),
        corectAn: 'Havana',
        ans: ['Panama', 'San José', 'San Juan', "Havana"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Chile?',
        img: require('../img/chiile.png'),
        corectAn: 'Santiago',
        ans: ['Bogota', 'San José', 'Lima', "Santiago"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Costa Rica?',
        img: require('../img/costa.png'),
        corectAn: 'San José',
        ans: ['Bogota', 'San José', 'Lima', "Santiago"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Ecuador?',
        img: require('../img/ecuador.png'),
        corectAn: 'Quito',
        ans: ['Bogota', 'Quito', 'Lima', "Santiago"],
        dificult: ['2', '3'],
        type: 'capital',
    },
    {
        question: 'What is the Capital of Honduras?',
        img: require('../img/honduras.png'),
        corectAn: 'Tegucigalpa',
        ans: ['Tegucigalpa', 'Quito', 'Lima', "Santiago"],
        dificult: ['3'],
        type: 'capital',
    },
    //Mount
    {
        question: 'Highest Mountain Peaks in the World?',
        img: require('../img/mount.jpg'),
        corectAn: 'Mount Everest',
        ans: ['Lhotse', 'Mount Everest', 'K2', "Kanchenjunga"],
        dificult: ['1', '2'],
        type: 'mountain',
    },
    {
        question: 'Highest Mountain Peaks in the Balkans?',
        img: require('../img/mount4.jpg'),
        corectAn: 'Rila',
        ans: ['Rila', 'Korab', 'Olimp', "Baba"],
        dificult: ['3'],
        type: 'mountain',
    },
    {
        question: 'Highest Mountain Peaks in the Europe?',
        img: require('../img/mount.jpg'),
        corectAn: 'Mount Elbrus',
        ans: ['Mount Elbrus', 'Mount Everest', 'K2', "Mont Blanc"],
        dificult: ['1', '2', '3'],
        type: 'mountain',
    },
    {
        question: 'Highest Mountain Peaks in the Africa?',
        img: require('../img/mount.jpg'),
        corectAn: 'Kilimanjaro',
        ans: ['Mount Meru', 'Mount Everest', 'Mount Kenya', "Kilimanjaro"],
        dificult: ['1', '2', '3'],
        type: 'mountain',
    },
    {
        question: 'Highest Mountain Peaks in the South America?',
        img: require('../img/mount2.jpg'),
        corectAn: 'Aconcagua',
        ans: ['Aconcagua', 'Mount Everest', 'Mount McKinley', "Tajumulco"],
        dificult: ['2', '3'],
        type: 'mountain',
    },
    {
        question: 'Highest Mountain Peaks in the China?',
        img: require('../img/mount2.jpg'),
        corectAn: 'Mount Everest',
        ans: ['Lhotse', 'Mount Everest', 'Kanchenjunga', "Tajumulco"],
        dificult: ['2', '3'],
        type: 'mountain',
    },
    {
        question: 'Highest Mountain Peaks in the India?',
        img: require('../img/mount2.jpg'),
        corectAn: 'Kanchenjunga',
        ans: ['Lhotse', 'Mount Everest', 'Kanchenjunga', "Nanda Devi"],
        dificult: ['2', '3'],
        type: 'mountain',
    },
    {
        question: 'Highest Mountain Peaks in the Spain?',
        img: require('../img/moun_3.jpg'),
        corectAn: 'Mount Teide',
        ans: ['Lhotse', 'Mount Teide', 'Mulhacén', "Nanda Devi"],
        dificult: ['2', '3'],
        type: 'mountain',
    },
    {
        question: 'Highest Mountain Peaks in the Iran?',
        img: require('../img/moun_3.jpg'),
        corectAn: 'Damavand',
        ans: ['Damavand', 'Alam-Kuh', 'Mulhacén', "Nanda Devi"],
        dificult: ['3'],
        type: 'mountain',
    },
    {
        question: 'Highest Mountain Peaks in the North America?',
        img: require('../img/mount2.jpg'),
        corectAn: 'Mount McKinley',
        ans: ['Aconcagua', 'Mount Everest', 'Mount McKinley', "Tajumulco"],
        dificult: ['2', '3'],
        type: 'mountain',
    },
    {
        question: 'Highest Mountain Peaks in the Russia?',
        img: require('../img/mount2.jpg'),
        corectAn: 'Mount Elbrus',
        ans: ['Mount Ural', 'Mount Kazbek', 'Dykh-Tau', "Mount Elbrus"],
        dificult: ['2', '3'],
        type: 'mountain',
    },
    //LAKE
    {
        question: 'Deepest lake in the world?',
        img: require('../img/lake.jpg'),
        corectAn: 'Lake Baikal',
        ans: ['Tanganyika', 'Lake Baikal', 'Lake Vostok', "Lake Malawi"],
        dificult: ['1', '2', '3'],
        type: 'lake',
    },
    {
        question: 'Largest lake in the world?',
        img: require('../img/lake.jpg'),
        corectAn: 'Caspian Sea',
        ans: ['Lake Michigan–Huron', 'Lake Baikal', 'Lake Victoria', "Caspian Sea"],
        dificult: ['2', '3'],
        type: 'lake',
    },
    {
        question: 'Largest lake in the Africa?',
        img: require('../img/lake.jpg'),
        corectAn: 'Lake Victoria',
        ans: ['Lake Michigan–Huron', 'Lake Baikal', 'Lake Victoria', "Lake Tanganyika"],
        dificult: ['2', '3'],
        type: 'lake',
    },
    {
        question: 'Largest lake in the North America?',
        img: require('../img/lake2.jpg'),
        corectAn: 'Lake Michigan–Huron',
        ans: ['Lake Michigan–Huron', 'Lake Superior', 'Lake Victoria', "Lake Huron"],
        dificult: ['2', '3'],
        type: 'lake',
    },
    {
        question: 'Largest lake in the South America?',
        img: require('../img/lake2.jpg'),
        corectAn: 'Lake Maracaibo',
        ans: ['Lake Titicaca', 'Lake Superior', 'Lake Maracaibo', "Lake Huron"],
        dificult: ['2', '3'],
        type: 'lake',
    },
    {
        question: 'Country with most Lake in the World?',
        img: require('../img/lake2.jpg'),
        corectAn: 'Canada',
        ans: ['USA', 'Finland', 'Russia', "Canada"],
        dificult: ['1', '2', '3'],
        type: 'lake',
    },
    // Deserts
    {
        question: 'Largest desert in the world?',
        img: require('../img/desert.jpg'),
        corectAn: 'Sahara',
        ans: ['Kalahari Desert', 'Arabian Desert', 'Gobi Desert', "Sahara"],
        dificult: ['1'],
        type: 'desert',
    },
    {
        question: 'Largest desert in the Asia?',
        img: require('../img/desert.jpg'),
        corectAn: 'Gobi Desert',
        ans: ['Kalahari Desert', 'Arabian Desert', 'Gobi Desert', "Sahara"],
        dificult: ['2', '3'],
        type: 'desert',
    },
    {
        question: 'Largest desert in the North America?',
        img: require('../img/desert.jpg'),
        corectAn: 'Great Basin Desert',
        ans: ['Kalahari Desert', 'Great Basin Desert', 'Gobi Desert', "Chihuahuan Desert"],
        dificult: ['2', '3'],
        type: 'desert',
    },
    {
        question: 'Second largest desert in the Africa?',
        img: require('../img/desert.jpg'),
        corectAn: 'Kalahari Desert',
        ans: ['Kalahari Desert', 'Arabian Desert', 'Gobi Desert', "Sahara"],
        dificult: ['2', '3'],
        type: 'desert',
    },
    {
        question: 'Largest desert in the South America?',
        img: require('../img/desert.jpg'),
        corectAn: 'Atacama Desert',
        ans: ['Kalahari Desert', 'Atacama Desert', 'Gobi Desert', "Sahara"],
        dificult: ['2', '3'],
        type: 'desert',
    },
    //Oceans
    {
        question: 'Deepest ocean in the world?',
        img: require('../img/ocean.jpg'),
        corectAn: 'Pacific Ocean',
        ans: ['Atlantic Ocean', 'Indian Ocean', 'Southern Ocean', "Pacific Ocean"],
        dificult: ['1', '2', '3'],
        type: 'ocean',
    },
    {
        question: 'Deepest place in the world?',
        img: require('../img/ocean.jpg'),
        corectAn: 'Mariana Trench',
        ans: ['Mariana Trench', 'Milwaukee Deep', 'Java Trench', "Puerto Rico Trench"],
        dificult: ['2', '3'],
        type: 'ocean',
    },
    {
        question: 'Smallest ocean in the world?',
        img: require('../img/ocean.jpg'),
        corectAn: 'Arctic Ocean',
        ans: ['Arctic Ocean', 'Atlantic Ocean', 'Pacific Ocean', "Indian Ocean"],
        dificult: ['2', '3'],
        type: 'ocean',
    },
    {
        question: 'How many oceans are there?',
        img: require('../img/ocean.jpg'),
        corectAn: '5',
        ans: ['7', '6', '5', "4"],
        dificult: ['1', '2'],
        type: 'ocean',
    },
    {
        question: 'How many oceans border the United States?',
        img: require('../img/ocean.jpg'),
        corectAn: '3',
        ans: ['3', '2', '5', "4"],
        dificult: ['1', '2'],
        type: 'ocean',
    },
    {
        question: 'How many oceans border the Russia?',
        img: require('../img/ocean.jpg'),
        corectAn: '2',
        ans: ['3', '2', '1', "4"],
        dificult: ['1', '2'],
        type: 'ocean',
    },
    {
        question: 'How many oceans border the South Africa?',
        img: require('../img/ocean.jpg'),
        corectAn: '2',
        ans: ['3', '2', '1', "4"],
        dificult: ['1', '2'],
        type: 'ocean',
    },
    // SEA
    {
        question: 'Largest sea in the world?',
        img: require('../img/sea.jpg'),
        corectAn: 'Coral Sea',
        ans: ['Mediterranean', 'Caribbean Sea', 'Coral Sea', "South China Sea"],
        dificult: ['2', '3'],
        type: 'sea',
    },
    {
        question: 'Largest sea in the Europe?',
        img: require('../img/sea.jpg'),
        corectAn: 'Mediterranean',
        ans: ['Mediterranean', 'Caribbean Sea', 'Coral Sea', "South China Sea"],
        dificult: ['1', '2'],
        type: 'sea',
    },
    {
        question: 'Deepest sea in the world?',
        img: require('../img/sea.jpg'),
        corectAn: 'Caribbean Sea',
        ans: ['Mediterranean', 'Caribbean Sea', 'Coral Sea', "South China Sea"],
        dificult: ['2', '3'],
        type: 'sea',
    },
    //SIZE
    {
        question: 'Largest country in the world?',
        img: require('../img/count.jpg'),
        corectAn: 'Russia',
        ans: ['Russia', 'US', 'Canada', "China"],
        dificult: ['1'],
        type: 'size',     
    },
    {
        question: 'Second largest country in the world?',
        img: require('../img/count.jpg'),
        corectAn: 'Canada',
        ans: ['Russia', 'US', 'Canada', "China"],
        dificult: ['1','2'],
        type: 'size',     
    },
    {
        question: 'Second largest country in the North America?',
        img: require('../img/count.jpg'),
        corectAn: 'US',
        ans: ['Russia', 'US', 'Canada', "China"],
        dificult: ['1','2'],
        type: 'size',     
    },
    {
        question: 'Largest country in the Africa?',
        img: require('../img/count.jpg'),
        corectAn: 'Algeria',
        ans: ['Libya', 'Congo', 'Sudan', "Algeria"],
        dificult: ['2','3'],
        type: 'size',     
    },
    {
        question: 'Second largest country in the Africa?',
        img: require('../img/count.jpg'),
        corectAn: 'Congo',
        ans: ['Libya', 'Congo', 'Sudan', "Algeria"],
        dificult: ['2','3'],
        type: 'size',     
    },
    {
        question: 'Second largest country in the South America?',
        img: require('../img/count.jpg'),
        corectAn: 'Argentina',
        ans: ['Argentina', 'Brazil', 'Peru', "Columbia"],
        dificult: ['2'],
        type: 'size',     
    },
    {
        question: 'Second largest country in the Europa?',
        img: require('../img/count.jpg'),
        corectAn: 'Ukraine',
        ans: ['Ukraine', 'Russia', 'France', "Sweden"],
        dificult: ['2','3'],
        type: 'size',     
    },
    {
        question: 'Second largest country in the Asia?',
        img: require('../img/count.jpg'),
        corectAn: 'China',
        ans: ['India', 'Russia', 'Iran', "China"],
        dificult: ['2','3'],
        type: 'size',     
    },
    {
        question: 'Largest country in the Middle East?',
        img: require('../img/count.jpg'),
        corectAn: 'Saudi Arabia',
        ans: ['India', 'Egypt', 'Iran', "Saudi Arabia"],
        dificult: ['2','3'],
        type: 'size',     
    },
    {
        question: 'Smallest country in the South America?',
        img: require('../img/small.jpg'),
        corectAn: 'Suriname',
        ans: ['Suriname', 'Ecuador', 'Peru', "Panama"],
        dificult: ['2','3'],
        type: 'size',     
    },
    {
        question: 'Smallest country in the Europe?',
        img: require('../img/small.jpg'),
        corectAn: 'Vatican City',
        ans: ['Andora', 'Monaco', 'Vatican City', "San Marino"],
        dificult: ['2','3'],
        type: 'size',     
    },
    {
        question: 'Smallest country in the Asia?',
        img: require('../img/small.jpg'),
        corectAn: 'Maldives',
        ans: ['Brunei', 'Bahrain', 'Singapore', "Maldives"],
        dificult: ['2','3'],
        type: 'size',     
    },
    //Country
    {
        question: 'Guess the country from its outline?',
        img: require('../img/alCou.png'),
        corectAn: 'Albania',
        ans: ['Albania', 'Macedonia', 'Montenegro', "Slovenia"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/mkCou.png'),
        corectAn: 'Macedonia',
        ans: ['Albania', 'Macedonia', 'Serbia', "Slovenia"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/grCou.png'),
        corectAn: 'Greece',
        ans: ['Greece', 'Macedonia', 'Serbia', "Bulgaria"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/srCou.png'),
        corectAn: 'Serbia',
        ans: ['Greece', 'Croatia', 'Serbia', "Bulgaria"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/bgCou.png'),
        corectAn: 'Bulgaria',
        ans: ['Greece', 'Croatia', 'Serbia', "Bulgaria"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/crCou.png'),
        corectAn: 'Croatia',
        ans: ['Greece', 'Croatia', 'Hungary', "Greece"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/slCou.png'),
        corectAn: 'Slovenia',
        ans: ['Slovakia', 'Croatia', 'Hungary', "Slovenia"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/boCou.png'),
        corectAn: 'Bosnia',
        ans: ['Montenegro', 'Croatia', 'Hungary', "Bosnia"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/mnCou.png'),
        corectAn: 'Montenegro',
        ans: ['Montenegro', 'Croatia', 'Macedonia', "Bosnia"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/huCou.png'),
        corectAn: 'Hungary',
        ans: ['Hungary', 'Croatia', 'Serbia', "Bulgaria"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/tuCou.png'),
        corectAn: 'Turkey',
        ans: ['Syria', 'Turkey', 'Iran', "Greece"],
        dificult: ['1','2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/roCou.png'),
        corectAn: 'Romania',
        ans: ['Hungary', 'Romania', 'Serbia', "Bulgaria"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/soCou.png'),
        corectAn: 'Slovakia',
        ans: ['Hungary', 'Czech Republic', 'Slovenia', "Slovakia"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/chCou.png'),
        corectAn: 'Czech Republic',
        ans: ['Hungary', 'Czech Republic', 'Slovenia', "Slovakia"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/auCou.png'),
        corectAn: 'Austria',
        ans: ['Hungary', 'Czech Republic', 'Austria', "Slovakia"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/itCou.png'),
        corectAn: 'Italy',
        ans: ['Spain', 'Italy', 'Yugoslavia', "France"],
        dificult: ['1','2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/frCou.png'),
        corectAn: 'France',
        ans: ['Spain', 'Italy', 'France', "Germany"],
        dificult: ['1','2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/spCou.png'),
        corectAn: 'Spain',
        ans: ['Spain', 'Italy', 'France', "Portugal"],
        dificult: ['1','2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/poCou.png'),
        corectAn: 'Portugal',
        ans: ['Spain', 'Italy', 'France', "Portugal"],
        dificult: ['1','2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/swCou.png'),
        corectAn: 'Switzerland',
        ans: ['Switzerland', 'Italy', 'France', "Austria"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/deCou.png'),
        corectAn: 'Germany',
        ans: ['UK', 'Italy', 'France', "Germany"],
        dificult: ['1'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/ukCou.png'),
        corectAn: 'UK',
        ans: ['UK', 'Italy', 'France', "Germany"],
        dificult: ['1'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/irCou.png'),
        corectAn: 'R.Irland',
        ans: ['R.Irland', 'UK', 'France', "Iceland"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/dnCou.png'),
        corectAn: 'Denmark',
        ans: ['Denmark', 'Norway', 'France', "Iceland"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/ruCou.png'),
        corectAn: 'Russia',
        ans: ['UK', 'Russia', 'China', "Usa"],
        dificult: ['1'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/ukrCou.png'),
        corectAn: 'Ukraine',
        ans: ['Ukraine', 'Russia', 'Poland', "Belarus"],
        dificult: ['1'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/plCou.png'),
        corectAn: 'Poland',
        ans: ['Ukraine', 'Russia', 'Poland', "Belarus"],
        dificult: ['1','2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/blCou.png'),
        corectAn: 'Belarus',
        ans: ['Ukraine', 'Russia', 'Poland', "Belarus"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/esCou.png'),
        corectAn: 'Estonia',
        ans: ['Estonia', 'Latvia', 'Poland', "Lithuania"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/lvCou.png'),
        corectAn: 'Latvia',
        ans: ['Estonia', 'Latvia', 'Poland', "Lithuania"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/liCou.png'),
        corectAn: 'Lithuania',
        ans: ['Estonia', 'Latvia', 'Poland', "Lithuania"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/nrCou.png'),
        corectAn: 'Norway',
        ans: ['Estonia', 'Sweden', 'Norway', "Lithuania"],
        dificult: ['2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/sweCou.png'),
        corectAn: 'Sweden',
        ans: ['Finland', 'Sweden', 'Norway', "Lithuania"],
        dificult: ['2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/fiCou.png'),
        corectAn: 'Finland',
        ans: ['Finland', 'Sweden', 'Norway', "Lithuania"],
        dificult: ['2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/cinCou.png'),
        corectAn: 'China',
        ans: ['Russia', 'China', 'India', "Japan"],
        dificult: ['1'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/jpCou.png'),
        corectAn: 'Japan',
        ans: ['S.Korea', 'China', 'N.Korea', "Japan"],
        dificult: ['1'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/caCou.png'),
        corectAn: 'Canada',
        ans: ['Canada', 'China', 'USA', "Russia"],
        dificult: ['1'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/usCou.png'),
        corectAn: 'USA',
        ans: ['Canada', 'China', 'USA', "Brazil"],
        dificult: ['1'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/mxCou.png'),
        corectAn: 'Mexico',
        ans: ['Cuba', 'Mexico', 'USA', "Brazil"],
        dificult: ['1','2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/prCou.png'),
        corectAn: 'Peru',
        ans: ['Peru', 'Paraguay', 'Bolivia', "Chile"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/arCou.png'),
        corectAn: 'Argentina',
        ans: ['Peru', 'Paraguay', 'Argentina', "Chile"],
        dificult: ['2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/cuCou.png'),
        corectAn: 'Cuba',
        ans: ['Cuba', 'Paraguay', 'Honduras', "Dominican Republic"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/venCou.png'),
        corectAn: 'Venezuela',
        ans: ['Venezuela', 'Paraguay', 'Columbia', "French Guiana"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/coCou.png'),
        corectAn: 'Columbia',
        ans: ['Venezuela', 'Mexico', 'Columbia', "French Guiana"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/gyCou.png'),
        corectAn: 'French Guiana',
        ans: ['Ecuador', 'Mexico', 'Cuba', "French Guiana"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/ecCou.png'),
        corectAn: 'Ecuador',
        ans: ['Ecuador', 'Mexico', 'Uruguay', "Paraguay"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/parCou.png'),
        corectAn: 'Paraguay',
        ans: ['Ecuador', 'Peru', 'Uruguay', "Paraguay"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/bolCou.png'),
        corectAn: 'Bolivia',
        ans: ['Ecuador', 'Peru', 'Bolivia', "Paraguay"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/brCou.png'),
        corectAn: 'Brazil',
        ans: ['USA', 'China', 'Brazil', "Argentina"],
        dificult: ['1'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/clCou.png'),
        corectAn: 'Chile',
        ans: ['Chile', 'Peru', 'Bolivia', "Paraguay"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/urCou.png'),
        corectAn: 'Uruguay',
        ans: ['Chile', 'Peru', 'Uruguay', "Paraguay"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/thCou.png'),
        corectAn: 'Thailand',
        ans: ['Myanmar', 'Vietnam', 'Thailand', "Cambodia"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/myCou.png'),
        corectAn: 'Myanmar',
        ans: ['Myanmar', 'Vietnam', 'Thailand', "Cambodia"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/vtCou.png'),
        corectAn: 'Vietnam',
        ans: ['Myanmar', 'Vietnam', 'Thailand', "Cambodia"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/camCou.png'),
        corectAn: 'Cambodia',
        ans: ['Myanmar', 'Vietnam', 'Thailand', "Cambodia"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/inCou.png'),
        corectAn: 'India',
        ans: ['Myanmar', 'Afganistan', 'Pakistan', "India"],
        dificult: ['1','2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/afgCou.png'),
        corectAn: 'Afganistan',
        ans: ['Iran', 'Afganistan', 'Pakistan', "India"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/pakCou.png'),
        corectAn: 'Pakistan',
        ans: ['Iran', 'Afganistan', 'Pakistan', "India"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/kzCou.png'),
        corectAn: 'Kazakhstan',
        ans: ['Kazakhstan', 'Kyrgyzstan', 'Uzbekistan', "Turkmenistan"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/kyCou.png'),
        corectAn: 'Kyrgyzstan',
        ans: ['Kazakhstan', 'Kyrgyzstan', 'Uzbekistan', "Turkmenistan"],
        dificult: ['3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/uzbCou.png'),
        corectAn: 'Uzbekistan',
        ans: ['Kazakhstan', 'Kyrgyzstan', 'Uzbekistan', "Turkmenistan"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/turkCou.png'),
        corectAn: 'Turkmenistan',
        ans: ['Kazakhstan', 'Kyrgyzstan', 'Uzbekistan', "Turkmenistan"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/iranCou.png'),
        corectAn: 'Iran',
        ans: ['Iran', 'Iraq', 'Syria', "Turkmenistan"],
        dificult: ['1','2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/iraqCou.png'),
        corectAn: 'Iraq',
        ans: ['Iran', 'Iraq', 'Syria', "Turkey"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/syCou.png'),
        corectAn: 'Syria',
        ans: ['Iran', 'Lebanon', 'Syria', "Jordan"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/lebCou.png'),
        corectAn: 'Lebanon',
        ans: ['Israel', 'Lebanon', 'Syria', "Jordan"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/isrCou.png'),
        corectAn: 'Israel',
        ans: ['Israel', 'Lebanon', 'Syria', "Jordan"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/jorCou.png'),
        corectAn: 'Jordan',
        ans: ['Israel', 'Lebanon', 'Syria', "Jordan"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/saudCou.png'),
        corectAn: 'Saudi Arabia',
        ans: ['Saudi Arabia', 'Lebanon', 'Jemen', "Jordan"],
        dificult: ['1','2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/omanCou.png'),
        corectAn: 'Oman',
        ans: ['Oman', 'Jemen', 'Syria', "Jordan"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/jemCou.png'),
        corectAn: 'Jemen',
        ans: ['Oman', 'Jemen', 'Syria', "Jordan"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/azCou.png'),
        corectAn: 'Azerbaijan',
        ans: ['Georgia', 'Azerbaijan', 'Syria', "Armenia"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/armCou.png'),
        corectAn: 'Armenia',
        ans: ['Georgia', 'Azerbaijan', 'Syria', "Armenia"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/geoCou.png'),
        corectAn: 'Georgia',
        ans: ['Georgia', 'Azerbaijan', 'Syria', "Armenia"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/uaeCou.png'),
        corectAn: 'UAE',
        ans: ['UAE', 'Kuwait', 'Syria', "Jemen"],
        dificult: ['3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/kuwCou.png'),
        corectAn: 'Kuwait',
        ans: ['UAE', 'Kuwait', 'Syria', "Jemen"],
        dificult: ['3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/egpCou.png'),
        corectAn: 'Egypt',
        ans: ['Tunis', 'Eritrea', 'Sudan', "Egypt"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/ertCou.png'),
        corectAn: 'Eritrea',
        ans: ['Ethiopia', 'Eritrea', 'Sudan', "Egypt"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/ethCou.png'),
        corectAn: 'Ethiopia',
        ans: ['Ethiopia', 'Eritrea', 'Sudan', "Egypt"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/souCou.png'),
        corectAn: 'Sudan',
        ans: ['Ethiopia', 'Libya', 'Sudan', "Egypt"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/tunCou.png'),
        corectAn: 'Tunis',
        ans: ['Tunis', 'Libya', 'Morocco', "Egypt"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/libCou.png'),
        corectAn: 'Libya',
        ans: ['Tunis', 'Libya', 'Morocco', "Egypt"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/algCou.png'),
        corectAn: 'Algeria',
        ans: ['Tunis', 'Libya', 'Morocco', "Algeria"],
        dificult: ['1','2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/marCou.png'),
        corectAn: 'Morocco',
        ans: ['Tunis', 'Libya', 'Morocco', "Algeria"],
        dificult: ['1','2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/nigCou.png'),
        corectAn: 'Niger',
        ans: ['Niger', 'Libya', 'Mali', "Algeria"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/malCou.png'),
        corectAn: 'Mali',
        ans: ['Niger', 'Libya', 'Mali', "Algeria"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/ssuCou.png'),
        corectAn: 'South Sudan',
        ans: ['Niger', 'Sudan', 'Mali', "South Sudan"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/carCou.png'),
        corectAn: 'CAR',
        ans: ['CAR', 'Sudan', 'Mali', "South Sudan"],
        dificult: ['3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/chdCou.png'),
        corectAn: 'Chad',
        ans: ['Chad', 'Sudan', 'Mali', "Togo"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/burCou.png'),
        corectAn: 'Burkina Faso',
        ans: ['Chad', 'Ivory Coast', 'Burkina Faso', "Togo"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/ivyCou.png'),
        corectAn: 'Ivory Coast',
        ans: ['Nigera', 'Ivory Coast', 'Burkina Faso', "Togo"],
        dificult: ['3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/togCou.png'),
        corectAn: 'Togo',
        ans: ['Nigera', 'Ivory Coast', 'Burkina Faso', "Togo"],
        dificult: ['3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/genCou.png'),
        corectAn: 'Guinea',
        ans: ['Guinea', 'Ivory Coast', 'Senegal', "Togo"],
        dificult: ['3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/senCou.png'),
        corectAn: 'Senegal',
        ans: ['Guinea', 'Mauritania', 'Senegal', "Togo"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/mauCou.png'),
        corectAn: 'Mauritania',
        ans: ['Guinea', 'Ivory Coast', 'Senegal', "Mauritania"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/gabCou.png'),
        corectAn: 'Gabon',
        ans: ['Republic of the Congo', 'Ivory Coast', 'Gabon', "Cameroon"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/konCou.png'),
        corectAn: 'Republic of the Congo',
        ans: ['Republic of the Congo', 'Ivory Coast', 'Gabon', "Cameroon"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/cameCou.png'),
        corectAn: 'Cameroon',
        ans: ['Republic of the Congo', 'Ivory Coast', 'Gabon', "Cameroon"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/zamCou.png'),
        corectAn: 'Zambia',
        ans: ['Angola', 'Nigeria', 'Zambia', "Cameroon"],
        dificult: ['1','2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/nigeCou.png'),
        corectAn: 'Nigeria',
        ans: ['Angola', 'Nigeria', 'Zambia', "Cameroon"],
        dificult: ['1','2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/angCou.png'),
        corectAn: 'Angola',
        ans: ['Angola', 'Nigeria', 'Zambia', "Cameroon"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/namCou.png'),
        corectAn: 'Nambia',
        ans: ['Angola', 'Nambia', 'Zambia', "Cameroon"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/soutCou.png'),
        corectAn: 'South Africa',
        ans: ['Angola', 'Nambia', 'Zambia', "South Africa"],
        dificult: ['1','2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/bocCou.png'),
        corectAn: 'Botswana',
        ans: ['Botswana', 'Nambia', 'Zambia', "South Africa"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/swizCou.png'),
        corectAn: 'Swaziland',
        ans: ['Botswana', 'Swaziland', 'Zambia', "South Africa"],
        dificult: ['3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/mozCou.png'),
        corectAn: 'Mozambique',
        ans: ['Botswana', 'Nambia', 'Zambia', "Mozambique"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/zimCou.png'),
        corectAn: 'Zimbabwe',
        ans: ['Zimbabwe', 'Nambia', 'Zambia', "Mozambique"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/madCou.png'),
        corectAn: 'Madagascar',
        ans: ['Zimbabwe', 'Nambia', 'Madagascar', "Mozambique"],
        dificult: ['1','2'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/kenyCou.png'),
        corectAn: 'Kenya',
        ans: ['Kenya', 'Somalia', 'Ethiopia', "Mozambique"],
        dificult: ['2','3'],
        type: 'country',     
    },
    {
        question: 'Guess the country from its outline?',
        img: require('../img/somCou.png'),
        corectAn: 'Somalia',
        ans: ['Kenya', 'Somalia', 'Ethiopia', "Mozambique"],
        dificult: ['2','3'],
        type: 'country',     
    },
    // RIVERS
    {
        question: 'What is the longest river in the world?',
        img: require('../img/river.jpg'),
        corectAn: 'Nile',
        ans: ['Mississippi', 'Yangtze', 'Nile', "Amazon"],
        dificult: ['1', '2'],
        type: 'river',
    },
    {
        question: 'What is the longest river in the Europe?',
        img: require('../img/rive.jpg'),
        corectAn: 'Volga',
        ans: ['Volga', 'Danube', 'Ural River', "Dnieper"],
        dificult: ['2', '3'],
        type: 'river',
    },
    {
        question: 'What is the longest river in the Sibir?',
        img: require('../img/ob.jpg'),
        corectAn: 'Ob River',
        ans: ['Volga', 'Irtysh River', 'Ural River', "Ob River"],
        dificult: ['2', '3'],
        type: 'river',
    },
    {
        question: 'What is the longest river in the India?',
        img: require('../img/rive.jpg'),
        corectAn: 'Indus River',
        ans: ['Brahmaputra River', 'Indus River', 'Yarlung ', "Ganges"],
        dificult: ['2', '3'],
        type: 'river',
    },
    {
        question: 'What is the longest river in the Australia?',
        img: require('../img/rive.jpg'),
        corectAn: 'Murray',
        ans: ['Volga', 'Darling', 'Murrumbidgee', "Murray"],
        dificult: ['2', '3'],
        type: 'river',
    },
    {
        question: 'What is the longest river in the Asia?',
        img: require('../img/riverj.jpg'),
        corectAn: 'Yangtze',
        ans: ['Yellow River', 'Yangtze', 'Murrumbidgee', "Irtysh"],
        dificult: ['2', '3'],
        type: 'river',
    },
    {
        question: 'What is the longest river in the North America?',
        img: require('../img/rive.jpg'),
        corectAn: 'Missouri',
        ans: ['Rio Grande', 'Yukon River', 'Mississippi', "Missouri"],
        dificult: ['2', '3'],
        type: 'river',
    },
    {
        question: 'Rivers whit largest discharge of water?',
        img: require('../img/river.jpg'),
        corectAn: 'Amazon',
        ans: ['Mississippi', 'Congo', 'Nile', "Amazon"],
        dificult: ['1', '2'],
        type: 'river',
    },
    {
        question: 'Rivers whit largest discharge of water in Africa?',
        img: require('../img/river.jpg'),
        corectAn: 'Congo',
        ans: ['Kasai', 'Congo', 'Nile', "Amazon"],
        dificult: ['2', '3'],
        type: 'river',
    },
];
var dif;
var difArray = [];
var easyQuest = [];
var normalQuest = [];
var hardQuest = [];
var difQuest_1 = [];
var difQuest_2 = [];
var difQuest_3 = [];
// AsyncStorage.getItem('dificult').then((data) => {
//     dif = data;
//     difarr();
// })

function difarr() {
    for (let x = 0; x < questions.length; x++) {
        if (questions[x].dificult.includes('1')) {
            easyQuest.push(questions[x]);
        }
        if (questions[x].dificult.includes('2')) {
            normalQuest.push(questions[x]);
        }
        if (questions[x].dificult.includes('3')) {
            hardQuest.push(questions[x]);
        }

    }
    // random();
    return easyQuest, normalQuest, hardQuest;
}

// function random() {
//     for (let i = 0; i < 20; i++) {
//         let num = Math.floor(Math.random() * easyQuest.length);
//         difQuest_1.push(easyQuest[num]);
//         easyQuest.splice(num, 1);
//     }
//     for (let i = 0; i < 20; i++) {
//         let num = Math.floor(Math.random() * normalQuest.length);
//         difQuest_2.push(normalQuest[num]);
//         normalQuest.splice(num, 1);
//     }
//     for (let i = 0; i < 20; i++) {
//         let num = Math.floor(Math.random() * hardQuest.length);
//         difQuest_3.push(hardQuest[num]);
//         hardQuest.splice(num, 1);
//     }
//     return difQuest_1, difQuest_2, difQuest_3;
// }
difarr();
// random();
// var dificulties = [difQuest_1, difQuest_2, difQuest_3];
var dificulties = [easyQuest, normalQuest, hardQuest];

export { dificulties };